cargo-features = ["per-package-target"]

[package]
name = "noraboot"
version = "0.1.0"
edition = "2021"
forced-target = "i686-unknown-none-norostbkernel"

[dependencies.compiler_builtins]
version = "0.1"
features = ["mem"]

[dependencies.rsdp]
version = "*"
